Refactor: Changed all internal references from ssl_public_key to ssl_ca (#383)
## Context
While performing smoke tests for landscape server and client, I ran into
a certificate error when trying to register my client to server.
```
ERROR    [MainThread] Error contacting the server at https://10.184.245.73/message-system.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/landscape/lib/fetch.py", line 131, in fetch
    curl.perform()
pycurl.error: (60, 'server certificate verification failed. CAfile: none CRLfile: none')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/landscape/client/exchange.py", line 73, in exchange_messages
    response_bytes = fetch(
                     ^^^^^^
  File "/usr/lib/python3/dist-packages/landscape/lib/fetch.py", line 133, in fetch
    raise PyCurlError(e.args[0], e.args[1])
landscape.lib.fetch.PyCurlError: Error 60: server certificate verification failed. CAfile: none CRLfile: none
2025-10-20 18:30:02,556 ERROR    [MainThread] Registration failed: 
The server's SSL information is incorrect or fails signature verification!
If the server is using a self-signed certificate, please ensure you supply it with the --ssl-ca parameter.
```

The immediate fix was to simply add in a "ssl_public_key" parameter in
the `/etc/landscape/client.conf` file. Since this worked, this indicated
that somewhere in the code, the client was referencing back to the
deprecated `ssl_public_key` name.

To ensure that the new name is used, the `dest` for the `ssl_ca` and
`ssl_public_key` parser are now both pointing to the same `dest` in
`landscape/client/deployment.py`. With this change, everything in the
code base that referenced to the old `ssl_public_key` must be changed to
`ssl_ca`.

## Manual Testing

1. Ensure that `make check` runs and passes all testcases
2. Connect the client to a server instance using only the `ssl_ca` name
and no `ssl_public_key` name